### ISSUE TITLE
Bug-if the Flight mode Ch is higher than Ch8, the software recognises only 5 positions not 6

### ISSUE THREAD

**Issue by JeyPi** [ArduPilot/ardupilot_wiki_copy#1]
Hi. First I would like to ask if it was possible in Mission planner to see  all the  channels the RC IN sends to Pixhawk. My radio send in 10 Ch, but the Mission planner displays only 8.

I think there is a bug in the Flight mode Channel PWM processing.
When I set it to for example Ch5 all works OK. When it is set to CH9 or 10, I get only 5 positions not 6. One is missing. The THREE channels (5,9,10) have exactly the same PWM outcome.
On the channel 5 the software recognises PWM 1231-1360
While on CH9 and 10 it does not.

Mission planner 1.3.9
Arduplane V3.7.1

**Comment by CraigElder** [comment]
@JeyPi , you are posting to an issues list for a copy of our documentation. Please post your support requests into the appropriate support forum http://discuss.ardupilot.org/. Thank you.
