### ISSUE TITLE
Rudder control in attitude controlled modes.

### ISSUE THREAD

**Issue by JeyPi** [ArduPilot/ardupilot_wiki_copy#2]
My plane has two ailerons, elevator and a rudder.
I would like to disable the rudder in Attitude control modes and have only the ailerons and the elevator to work during these modes.
On the other hand I would like to have the rudder working during auto takeoff and autoland.
Any help?

**Comment by CraigElder** [comment]
@JeyPi , you are posting to an issues list for a copy of our documentation. Please post your support requests into the appropriate support forum http://discuss.ardupilot.org/.  Thank you.
